// swift-tools-version: 5.8

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Student Swift Colors",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "Student Swift Colors",
            targets: ["AppModule"],
            bundleIdentifier: "com.ZackWilson.Student-Swift-Colors",
            teamIdentifier: "3ZWQ27S93Y",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.yellow),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .camera(purposeString: "This app requires access to the camera to allow users to take photos for color analysis."),
                .photoLibrary(purposeString: "This app requires access to your photo library to select images for color analysis."),
                .photoLibraryAdd(purposeString: "This app needs to save color-analyzed images to your photo library.")
            ],
            appCategory: .graphicsDesign
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ]
)